name: NBA50 DoorDash Monitor

on:
  schedule:
    # NBA比赛通常在美东时间晚上7-10点开始，比赛持续2-3小时
    # 在比赛结束后的时间段运行检查（美东时间11PM, 1AM, 3AM）
    # 对应UTC时间 4AM, 6AM, 8AM
    - cron: '0 4,6,8 * * *'
  workflow_dispatch: # 允许你手动点击按钮测试

jobs:
  check_nba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests nba_api

      - name: Run Monitor
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python nba.py
